/* Start cas session */
cas mysess;
caslib _all_ assign;

/* Create Input Params Table */

data cc.input_opt_parameters_nat;
length 
	SCENARIO_NAME $20
	FACILITY $10
	SERVICE_LINE $10
	SUB_SERVICE $10
	IP_OP_INDICATOR $3
	MED_SURG_INDICATOR $4
	PARM_NAME $32 
	PARM_VALUE $15;
input 
	SCENARIO_NAME $
	FACILITY $
	SERVICE_LINE $
	SUB_SERVICE $
	IP_OP_INDICATOR $
	MED_SURG_INDICATOR $
	PARM_NAME $
	PARM_VALUE $;
datalines;
ICU_100 ALL ALL ALL ALL ALL ALLOW_OPENING_ONLY_ON_PHASE 1
ICU_100 ALL ALL ALL ALL ALL TEST_DAYS_BA 2
ICU_100 ALL ALL ALL ALL ALL RAPID_TEST_DA 100
ICU_100 ALL ALL ALL ALL ALL PLANNING_HORIZON 5
ICU_100 ALL ALL ALL ALL ALL DATE_PHASE_1 4/27/2020
ICU_100 ALL ALL ALL ALL ALL NOT_RAPID_TESTS_PHASE_1 1200
ICU_100 ALL ALL ALL ALL ALL RAPID_TESTS_PHASE_1 190
ICU_100 ALL ALL ALL ALL ALL DATE_PHASE_2 5/15/2020
ICU_100 ALL ALL ALL ALL ALL NOT_RAPID_TESTS_PHASE_2 1200
ICU_100 ALL ALL ALL ALL ALL RAPID_TESTS_PHASE_2 1908
ICU_100 ALL ALL ALL ALL ALL ICU_MAX_UTILIZATION 100
ICU_50 ALL ALL ALL ALL ALL ALLOW_OPENING_ONLY_ON_PHASE 1
ICU_50 ALL ALL ALL ALL ALL TEST_DAYS_BA 2
ICU_50 ALL ALL ALL ALL ALL RAPID_TEST_DA 100
ICU_50 ALL ALL ALL ALL ALL PLANNING_HORIZON 5
ICU_50 ALL ALL ALL ALL ALL DATE_PHASE_1 4/27/2020
ICU_50 ALL ALL ALL ALL ALL NOT_RAPID_TESTS_PHASE_1 1200
ICU_50 ALL ALL ALL ALL ALL RAPID_TESTS_PHASE_1 190
ICU_50 ALL ALL ALL ALL ALL DATE_PHASE_2 5/15/2020
ICU_50 ALL ALL ALL ALL ALL NOT_RAPID_TESTS_PHASE_2 1200
ICU_50 ALL ALL ALL ALL ALL RAPID_TESTS_PHASE_2 1908
ICU_50 ALL ALL ALL ALL ALL ICU_MAX_UTILIZATION 50
;
run;

/* 1 ALL ALL ALL ALL ALL REMOVE_DEMAND_CONSTRAINTS YES */
/* 1 ALL ALL ALL ALL ALL FILTER_SERV_NOT_USING_RESOURCES YES */
/* HOLD_RAPID_COVID_TESTS */
/* 1 ALL ALL ALL ALL ALL MIN_DEMAND_RATIO 50 */
/* ICU_100 ALL ALL ALL ALL ALL REMOVE_COVID_CONSTRAINTS YES */
/* ICU_50 ALL ALL ALL ALL ALL REMOVE_COVID_CONSTRAINTS YES */

