/* Start cas session */
cas mysess;
caslib _all_ assign;

/* Create Input Params Table */

data cc.input_opt_parameters_test;
   length
      SCENARIO_NAME $20
      FACILITY $10
      SERVICE_LINE $10
      SUB_SERVICE $10
      IP_OP_INDICATOR $3
      MED_SURG_INDICATOR $4
      PARM_NAME $32
      PARM_VALUE $15;
   input
      SCENARIO_NAME $
      FACILITY $
      SERVICE_LINE $
      SUB_SERVICE $
      IP_OP_INDICATOR $
      MED_SURG_INDICATOR $
      PARM_NAME $
      PARM_VALUE $;
datalines;
ALL ALL ALL ALL ALL ALL ALLOW_OPENING_ONLY_ON_PHASE YES
ALL ALL ALL ALL ALL ALL TEST_DAYS_BA 2
ALL ALL ALL ALL ALL ALL RAPID_TEST_DA 100
ALL ALL ALL ALL ALL ALL PLANNING_HORIZON 4
ALL ALL ALL ALL ALL ALL DATE_PHASE_1 5/15/2020
ALL ALL ALL ALL ALL ALL NOT_RAPID_TESTS_PHASE_1 1200
ALL ALL ALL ALL ALL ALL RAPID_TESTS_PHASE_1 1908
BASIC_SCEN ALL ALL ALL ALL ALL ICU_MAX_UTILIZATION 100
99_ICU_100 ALL ALL ALL ALL ALL ICU_MAX_UTILIZATION 100
9_ICU_90 ALL ALL ALL ALL ALL ICU_MAX_UTILIZATION 90
8_ICU_80 ALL ALL ALL ALL ALL ICU_MAX_UTILIZATION 80
7_ICU_70 ALL ALL ALL ALL ALL ICU_MAX_UTILIZATION 70
6_ICU_60 ALL ALL ALL ALL ALL ICU_MAX_UTILIZATION 60
5_ICU_50 ALL ALL ALL ALL ALL ICU_MAX_UTILIZATION 50
4_ICU_40 ALL ALL ALL ALL ALL ICU_MAX_UTILIZATION 40
3_ICU_30 ALL ALL ALL ALL ALL ICU_MAX_UTILIZATION 30
2_ICU_20 ALL ALL ALL ALL ALL ICU_MAX_UTILIZATION 20
1_ICU_10 ALL ALL ALL ALL ALL ICU_MAX_UTILIZATION 10
0_ICU_0 ALL ALL ALL ALL ALL ICU_MAX_UTILIZATION 0
;
run;

/* 1 ALL ALL ALL ALL ALL REMOVE_DEMAND_CONSTRAINTS YES */
/* 1 ALL ALL ALL ALL ALL FILTER_SERV_NOT_USING_RESOURCES YES */
/* HOLD_RAPID_COVID_TESTS */
/* 1 ALL ALL ALL ALL ALL MIN_DEMAND_RATIO 50 */
/* ICU_100 ALL ALL ALL ALL ALL REMOVE_COVID_CONSTRAINTS YES */
/* ICU_50 ALL ALL ALL ALL ALL REMOVE_COVID_CONSTRAINTS YES */

/* BASIC_SCEN ALL ALL ALL ALL ALL SECONDARY_OBJECTIVE_TOLERANCE 95 */
/* REV_TOL_100 ALL ALL ALL ALL ALL SECONDARY_OBJECTIVE_TOLERANCE 100 */
/* REV_TOL_99 ALL ALL ALL ALL ALL SECONDARY_OBJECTIVE_TOLERANCE 99 */
/* REV_TOL_98 ALL ALL ALL ALL ALL SECONDARY_OBJECTIVE_TOLERANCE 98 */

