/* Create Input Params Table */

data cc.input_opt_parameters_nat;
length 
	FACILITY $10
	SERVICE_LINE $10
	SUB_SERVICE $10
	IP_OP_INDICATOR $3
	MED_SURG_INDICATOR $4
	PARM_NAME $32 
	PARM_VALUE $15;
input 
	FACILITY $
	SERVICE_LINE $
	SUB_SERVICE $
	IP_OP_INDICATOR $
	MED_SURG_INDICATOR $
	PARM_NAME $
	PARM_VALUE $;
datalines;
ALL ALL ALL ALL ALL RAPID_TEST_DA 2
ALL ALL ALL ALL ALL PLANNING_HORIZON 5
ALL ALL ALL ALL ALL MIN_DEMAND_RATIO 50
ALL ALL ALL ALL ALL DATE_PHASE_1 4/27/2020
ALL ALL ALL ALL ALL NOT_RAPID_TESTS_PHASE_1 1200
ALL ALL ALL ALL ALL RAPID_TESTS_PHASE_1 190
ALL ALL ALL ALL ALL DATE_PHASE_2 5/15/2020
ALL ALL ALL ALL ALL NOT_RAPID_TESTS_PHASE_2 1200
ALL ALL ALL ALL ALL RAPID_TESTS_PHASE_2 1908
ALL ALL ALL ALL ALL OPTIMIZATION_START_DATE PHASE_1_DATE
ALL ALL ALL ALL ALL REMOVE_DEMAND_CONSTRAINTS YES
ALL ALL ALL ALL ALL FILTER_SERV_NOT_USING_RESOURCES YES
;
run;

